# Generated by Django 2.1.3 on 2018-11-06 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fichier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('prenom', models.CharField(max_length=120)),
                ('numero_electeur', models.CharField(max_length=120, unique=True)),
                ('numero_identification', models.CharField(max_length=120)),
                ('date_naissance', models.CharField(max_length=120)),
                ('lieu_naissance', models.CharField(max_length=120)),
                ('commune', models.CharField(max_length=120)),
                ('departement', models.CharField(max_length=120)),
                ('region', models.CharField(default='', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Parraine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('prenom', models.CharField(max_length=120)),
                ('numero_electeur', models.CharField(max_length=120, unique=True)),
                ('numero_identification', models.CharField(max_length=120)),
                ('date_naissance', models.CharField(max_length=120)),
                ('lieu_naissance', models.CharField(max_length=120)),
                ('commune', models.CharField(max_length=120)),
                ('departement', models.CharField(max_length=120)),
                ('region', models.CharField(default='', max_length=120)),
            ],
        ),
    ]
